services:
  backend:
    image: ${LOCAL_IMAGE_NAME}
    ports:
      - "8080:8080"
    environment:
      - PREDICTIONS_STREAM_NAME=ride_predictions
      - RUN_ID='Test'
      - TEST_RUN=True
      - AWS_DEFAULT_REGION=eu-west-1
      - MODEL_LOCATION=/app/model
    volumes:
      -"./model:/app/model"